name: wazo_dart
description: This is a wrapper around the Wazo Community REST API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-182.2.beta <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dotenv: ^3.0.0
  uuid: ^3.0.6
  
dependencies: {http: ^0.13.4}
